// stockGenerationService.js - Enhanced Stock Generation with LLM + Finnhub
import { doc, getDoc, setDoc, collection, getDocs, deleteDoc, updateDoc } from 'firebase/firestore';
import { db } from '../firebase';
import llmService from './llmService';
import groqService from './groqService';
import { getStockQuote, getCompanyProfile } from './finnhubService';

class StockGenerationService {
  constructor() {
    this.userId = null;
    this.riskProfile = null;
    this.userPreferences = null;
  }

  // Load user context for stock generation
  async loadUserContext() {
    try {
      const { getAuth } = await import('firebase/auth');
      const auth = getAuth();
      const user = auth.currentUser;
      
      if (!user) {
        console.error('❌ No authenticated user found');
        return false;
      }

      this.userId = user.uid;
      console.log('👤 Loading context for user:', this.userId);

      // Load user data
      const userDoc = await getDoc(doc(db, 'users', this.userId));
      const userData = userDoc.data();
      
      this.userPreferences = {
        likedStocks: userData?.likedStocks || [],
        rejectedStocks: userData?.rejectedStocks || [],
        portfolio: userData?.portfolio || [],
        cashBalance: userData?.cashBalance || 100000,
      };

      // Load risk profile from quiz results
      const riskDoc = await getDoc(doc(db, 'users', this.userId, 'preferences', 'quiz'));
      const riskData = riskDoc.data();
      
      this.riskProfile = riskData?.riskProfile || {
        volatility: 10,
        timeHorizon: 3,
        knowledge: 2,
        ethics: 3,
        liquidity: 2
      };

      console.log('✅ User context loaded successfully');
      console.log('📊 Risk profile:', this.riskProfile);
      console.log('📊 User preferences:', this.userPreferences);
      
      return true;
    } catch (error) {
      console.error('❌ Error loading user context:', error);
      return false;
    }
  }

  // Generate initial 10 stock recommendations after risk quiz
  async generateInitialRecommendations() {
    try {
      console.log('🎯 Generating initial 10 stock recommendations...');
      
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          throw new Error('Failed to load user context');
        }
      }

      // Get 10 LLM recommendations using Groq
      const recommendations = await groqService.getRecommendations(10);
      console.log(`✅ Groq LLM generated ${recommendations.length} initial recommendations`);

      if (!recommendations || recommendations.length === 0) {
        console.warn('⚠️ No LLM recommendations received');
        throw new Error('No stock recommendations generated by LLM');
      }

      // Fetch real data for each recommendation
      const stocksWithRealData = [];
      
      for (const recommendation of recommendations) {
        try {
          console.log(`📊 Processing initial recommendation: ${recommendation.symbol}`);
          
          // Get real-time quote data
          const quoteData = await getStockQuote(recommendation.symbol);
          
          // Get company profile data
          const companyData = await getCompanyProfile(recommendation.symbol);
          
          // Generate detailed analysis using LLM
          const analysis = await this.generateStockAnalysis(recommendation.symbol, companyData, quoteData);
          
          // Combine LLM analysis with real data
          const stock = {
            symbol: recommendation.symbol,
            name: companyData.name,
            price: quoteData.price,
            priceFormatted: `$${quoteData.price.toFixed(2)}`,
            change: quoteData.change,
            changePercent: quoteData.changePercent,
            sector: recommendation.sector || companyData.finnhubIndustry,
            industry: recommendation.industry || companyData.finnhubIndustry,
            description: companyData.weburl ? `Visit ${companyData.weburl}` : 'Company information available',
            website: companyData.weburl,
            logo: companyData.logo,
            marketCap: companyData.marketCapitalization ? `${(companyData.marketCapitalization / 1e9).toFixed(2)}B` : 'N/A',
            peRatio: 'N/A',
            dividendYield: 'N/A',
            growth: '',
            riskLevel: recommendation.riskLevel || 'medium',
            confidence: recommendation.confidence || 0.7,
            reason: recommendation.reason || 'AI-generated recommendation',
            riskMetrics: { beta: 'N/A', volatility: Math.abs(quoteData.change) },
            timestamp: Date.now(),
            lastUpdated: new Date().toISOString(),
            analysis: analysis.summary,
            investmentThesis: analysis.investmentThesis,
            keyRisks: analysis.keyRisks,
            keyBenefits: analysis.keyBenefits,
            targetPrice: `$${(quoteData.price * 1.1).toFixed(2)}`,
            recommendation: recommendation.recommendation || 'buy',
            generatedAt: new Date().toISOString(),
            source: 'LLM + Real-time Data',
            isInitialRecommendation: true
          };

          stocksWithRealData.push(stock);
          console.log(`✅ Successfully processed initial ${recommendation.symbol}`);
          
        } catch (error) {
          console.warn(`⚠️ Failed to process initial ${recommendation.symbol}:`, error.message);
          continue;
        }
      }

      console.log(`✅ Generated ${stocksWithRealData.length} initial stocks with real data`);
      
      // Store initial recommendations
      if (stocksWithRealData.length > 0) {
        await this.storeGeneratedStocks(stocksWithRealData);
        console.log(`✅ Successfully stored ${stocksWithRealData.length} initial stocks`);
        
        // Verify storage by retrieving stocks
        const storedStocks = await this.getGeneratedStocks();
        console.log(`🔍 Verification: Retrieved ${storedStocks.length} stored stocks`);
      } else {
        console.warn('⚠️ No stocks to store - all stocks failed to process');
      }
      
      return stocksWithRealData;
      
    } catch (error) {
      console.error('❌ Error generating initial recommendations:', error);
      throw error;
    }
  }

  // Generate detailed stock analysis using LLM
  async generateStockAnalysis(symbol, companyData, quoteData) {
    try {
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          console.error('❌ Failed to load user context for stock analysis');
          return {
            summary: `${symbol} shows potential for growth based on current market conditions and company fundamentals.`,
            investmentThesis: `${symbol} represents a solid investment opportunity with balanced risk-reward profile.`,
            keyBenefits: ['Growth potential', 'Strong fundamentals'],
            keyRisks: ['Market volatility', 'Sector-specific risks']
          };
        }
      }
      
      const prompt = `Analyze ${symbol} (${companyData.name}) for investment purposes. 
      
      Company Info: ${companyData.name}, ${companyData.finnhubIndustry || 'Technology'} sector, Market Cap: ${companyData.marketCapitalization ? `${(companyData.marketCapitalization / 1e9).toFixed(2)}B` : 'N/A'}
      Current Price: $${quoteData.price}, Change: ${quoteData.changePercent}, Volume: ${quoteData.volume || 'N/A'}
      
      User Risk Profile: ${this.getRiskLevel(this.riskProfile.volatility)} (${this.riskProfile.volatility}/10)
      Investment Horizon: ${this.getTimeHorizon(this.riskProfile.timeHorizon)}
      Investment Knowledge: ${this.getKnowledgeLevel(this.riskProfile.knowledge)}
      
      Based on the real-time pricing data and user's risk profile, provide:
      1. A 100-word investment analysis summary tailored to this user
      2. Investment thesis (2-3 sentences) using current market data
      3. 2 key benefits for this user's specific risk profile
      4. 2 key risks for this user's specific risk profile
      
      Format as JSON:
      {
        "summary": "100-word analysis...",
        "investmentThesis": "Thesis...",
        "keyBenefits": ["Benefit 1", "Benefit 2"],
        "keyRisks": ["Risk 1", "Risk 2"]
      }`;

      const response = await groqService.callLLM(prompt);
      const analysis = JSON.parse(response);
      
      return {
        summary: analysis.summary,
        investmentThesis: analysis.investmentThesis,
        keyBenefits: analysis.keyBenefits,
        keyRisks: analysis.keyRisks
      };
    } catch (error) {
      console.error(`❌ Error generating analysis for ${symbol}:`, error);
      // Return a more generic analysis instead of hardcoded one
      return {
        summary: `Analysis for ${symbol} could not be generated due to an error. Please try again.`,
        investmentThesis: `Unable to generate investment thesis for ${symbol} at this time.`,
        keyBenefits: ['Analysis unavailable'],
        keyRisks: ['Analysis unavailable']
      };
    }
  }

  // Record user choice (like/reject) for LLM learning
  async recordUserChoice(symbol, choice, stockData) {
    try {
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          console.error('❌ Failed to load user context for recording choice');
          return;
        }
      }

      const choiceData = {
        symbol,
        choice, // 'like' or 'reject'
        stockData,
        timestamp: new Date().toISOString(),
        riskProfile: this.riskProfile
      };

      // Store choice for LLM learning
      await setDoc(
        doc(db, 'users', this.userId, 'stockChoices', `${symbol}_${Date.now()}`),
        choiceData
      );

      // Update user preferences
      if (choice === 'like') {
        if (!this.userPreferences.likedStocks.includes(symbol)) {
          this.userPreferences.likedStocks.push(symbol);
        }
      } else {
        if (!this.userPreferences.rejectedStocks.includes(symbol)) {
          this.userPreferences.rejectedStocks.push(symbol);
        }
      }

      // Update user document
      await updateDoc(doc(db, 'users', this.userId), {
        likedStocks: this.userPreferences.likedStocks,
        rejectedStocks: this.userPreferences.rejectedStocks
      });

      console.log(`✅ Recorded ${choice} choice for ${symbol}`);
    } catch (error) {
      console.error(`❌ Error recording choice for ${symbol}:`, error);
    }
  }

  // Generate personalized stock recommendations using LLM with learning
  async generatePersonalizedStocks(maxStocks = 5) {
    try {
      console.log('🤖 Generating personalized stocks with learning...');
      
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          throw new Error('Failed to load user context');
        }
      }

      // Get LLM recommendations with learning context using Groq
      const recommendations = await groqService.getRecommendations(maxStocks);
      console.log(`✅ Groq LLM generated ${recommendations.length} recommendations`);

      if (!recommendations || recommendations.length === 0) {
        console.warn('⚠️ No LLM recommendations received');
        throw new Error('No stock recommendations generated by LLM');
      }

      // Filter out already liked/rejected stocks
      const availableStocks = recommendations.filter(rec => 
        !this.userPreferences.likedStocks.includes(rec.symbol) &&
        !this.userPreferences.rejectedStocks.includes(rec.symbol)
      );

      console.log(`📊 ${availableStocks.length} stocks available after filtering`);

      // Fetch real data for each recommendation
      const stocksWithRealData = [];
      
      for (const recommendation of availableStocks) {
        try {
          console.log(`📊 Processing recommendation: ${recommendation.symbol}`);
          
          // Get real-time quote data
          const quoteData = await getStockQuote(recommendation.symbol);
          
          // Get company profile data
          const companyData = await getCompanyProfile(recommendation.symbol);
          
          // Generate detailed analysis
          const analysis = await this.generateStockAnalysis(recommendation.symbol, companyData, quoteData);
          
          // Combine LLM analysis with real data
          const stock = {
            symbol: recommendation.symbol,
            name: companyData.name,
            price: quoteData.price,
            priceFormatted: `$${quoteData.price.toFixed(2)}`,
            change: quoteData.change,
            changePercent: quoteData.changePercent,
            sector: recommendation.sector || companyData.finnhubIndustry,
            industry: recommendation.industry || companyData.finnhubIndustry,
            description: companyData.weburl ? `Visit ${companyData.weburl}` : 'Company information available',
            website: companyData.weburl,
            logo: companyData.logo,
            marketCap: companyData.marketCapitalization ? `${(companyData.marketCapitalization / 1e9).toFixed(2)}B` : 'N/A',
            peRatio: 'N/A',
            dividendYield: 'N/A',
            growth: '',
            riskLevel: recommendation.riskLevel || 'medium',
            confidence: recommendation.confidence || 0.7,
            reason: recommendation.reason || 'AI-generated recommendation',
            riskMetrics: { beta: 'N/A', volatility: Math.abs(quoteData.change) },
            timestamp: Date.now(),
            lastUpdated: new Date().toISOString(),
            analysis: analysis.summary,
            investmentThesis: analysis.investmentThesis,
            keyRisks: analysis.keyRisks,
            keyBenefits: analysis.keyBenefits,
            targetPrice: `$${(quoteData.price * 1.1).toFixed(2)}`,
            recommendation: recommendation.recommendation || 'buy',
            generatedAt: new Date().toISOString(),
            source: 'LLM + Real-time Data'
          };

          stocksWithRealData.push(stock);
          console.log(`✅ Successfully processed ${recommendation.symbol}`);
          
        } catch (error) {
          console.warn(`⚠️ Failed to process ${recommendation.symbol}:`, error.message);
          continue;
        }
      }

      console.log(`✅ Generated ${stocksWithRealData.length} stocks with real data`);
      return stocksWithRealData;
      
    } catch (error) {
      console.error('❌ Error generating personalized stocks:', error);
      throw error;
    }
  }

  // Generate daily stocks for swiping (exactly 10 stocks = 5 pairs)
  async generateDailyStocks() {
    try {
      console.log('📅 Generating exactly 10 stocks (5 pairs)...');
      
      // Load user context first
      const contextLoaded = await this.loadUserContext();
      if (!contextLoaded) {
        console.error('❌ Failed to load user context');
        throw new Error('Failed to load user context');
      }
      
      // Get exactly 10 personalized recommendations
      const recommendedStocks = await this.generatePersonalizedStocks(10);
      
      if (!recommendedStocks || recommendedStocks.length === 0) {
        console.warn('⚠️ No personalized stocks generated');
        throw new Error('No personalized stocks generated');
      }

      // Ensure we have exactly 10 stocks
      if (recommendedStocks.length < 10) {
        console.warn(`⚠️ Only generated ${recommendedStocks.length} stocks, need 10`);
        throw new Error(`Only generated ${recommendedStocks.length} stocks, need 10`);
      }

      // Store the generated stocks
      await this.storeGeneratedStocks(recommendedStocks);
      
      console.log(`✅ Generated and stored exactly ${recommendedStocks.length} daily stocks`);
      return recommendedStocks;
      
    } catch (error) {
      console.error('❌ Error generating daily stocks:', error);
      throw error;
    }
  }

  // Store generated stocks in Firebase
  async storeGeneratedStocks(stocks) {
    try {
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          console.error('❌ Failed to load user context for storing stocks');
          return;
        }
      }

      // Clear old stocks first
      const oldStocksRef = collection(db, 'users', this.userId, 'generatedStocks');
      const oldStocksSnapshot = await getDocs(oldStocksRef);
      
      for (const doc of oldStocksSnapshot.docs) {
        await deleteDoc(doc.ref);
      }

      // Store new stocks
      console.log(`💾 Storing ${stocks.length} stocks for user: ${this.userId}`);
      for (const stock of stocks) {
        console.log(`📝 Storing stock: ${stock.symbol} - ${stock.name}`);
        await setDoc(
          doc(db, 'users', this.userId, 'generatedStocks', stock.symbol),
          {
            ...stock,
            storedAt: new Date().toISOString()
          }
        );
      }

      console.log(`✅ Stored ${stocks.length} stocks in Firebase`);
    } catch (error) {
      console.error('❌ Error storing generated stocks:', error);
    }
  }

  // Get stored generated stocks
  async getGeneratedStocks() {
    try {
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          console.error('❌ Failed to load user context for generated stocks');
          return [];
        }
      }

      console.log(`🔍 Fetching stocks for user: ${this.userId}`);
      const stocksRef = collection(db, 'users', this.userId, 'generatedStocks');
      const snapshot = await getDocs(stocksRef);
      
      console.log(`📊 Firebase returned ${snapshot.docs.length} documents`);
      
      const stocks = [];
      snapshot.forEach(doc => {
        const stockData = doc.data();
        console.log(`📋 Stock document: ${doc.id}`, {
          symbol: stockData.symbol,
          name: stockData.name,
          price: stockData.price
        });
        stocks.push({ ...stockData, id: doc.id });
      });

      console.log(`✅ Retrieved ${stocks.length} stored stocks`);
      return stocks;
    } catch (error) {
      console.error('❌ Error getting generated stocks:', error);
      return [];
    }
  }

  // Get stock pairs for side-by-side comparison
  async getStockPairs() {
    try {
      // Load user context if not already loaded
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          console.error('❌ Failed to load user context for stock pairs');
          return [];
        }
      }
      
      const stocks = await this.getGeneratedStocks();
      const pairs = [];
      
      for (let i = 0; i < stocks.length - 1; i += 2) {
        pairs.push({
          left: stocks[i],
          right: stocks[i + 1]
        });
      }
      
      // If odd number, add last stock with null right
      if (stocks.length % 2 === 1) {
        pairs.push({
          left: stocks[stocks.length - 1],
          right: null
        });
      }
      
      return pairs;
    } catch (error) {
      console.error('❌ Error getting stock pairs:', error);
      return [];
    }
  }

  // No fallback stocks - only real LLM-generated stocks
  getFallbackStocks() {
    console.log('❌ No fallback stocks available - only real LLM-generated stocks');
    throw new Error('No fallback stocks available. Only real LLM-generated stocks are supported.');
  }

  // Clear all cached stocks from Firebase
  async clearAllStocks() {
    try {
      if (!this.userId) {
        const contextLoaded = await this.loadUserContext();
        if (!contextLoaded) {
          throw new Error('Failed to load user context');
        }
      }

      console.log('🧹 Clearing all cached stocks...');
      const stocksRef = collection(db, 'users', this.userId, 'generatedStocks');
      const snapshot = await getDocs(stocksRef);
      
      for (const doc of snapshot.docs) {
        await deleteDoc(doc.ref);
      }
      
      console.log(`✅ Cleared ${snapshot.docs.length} cached stocks`);
    } catch (error) {
      console.error('❌ Error clearing stocks:', error);
      throw error;
    }
  }

  // Get risk level description
  getRiskLevel(volatility) {
    if (volatility <= 3) return 'Conservative';
    if (volatility <= 7) return 'Moderate';
    return 'Aggressive';
  }

  // Get time horizon description
  getTimeHorizon(timeHorizon) {
    if (timeHorizon <= 1) return 'Short-term (1-2 years)';
    if (timeHorizon <= 3) return 'Medium-term (3-5 years)';
    return 'Long-term (5+ years)';
  }

  // Get knowledge level description
  getKnowledgeLevel(knowledge) {
    if (knowledge <= 1) return 'Beginner';
    if (knowledge <= 2) return 'Intermediate';
    if (knowledge <= 3) return 'Advanced';
    return 'Expert';
  }
}

export default new StockGenerationService(); 